version: '3'

services:
  canal-backend:
    image: vivaconagua/canal-backend:0.0.1
    build: .
    container_name: canal-backend
    restart: unless-stopped
    volumes:
      - ./canal/settings.py:/app/canal/settings.py
    networks:
      default:
        ipv4_address: 172.2.0.33

  canal-database:
    image: mariadb:latest
    container_name: canal-database
    restart: unless-stopped
    volumes:
      - ./volumes/canal-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=canal
      - MYSQL_DATABASE=canal-database
      - MYSQL_USER=canal-database
      - MYSQL_PASSWORD=canal-database
      - MYSQL_ROOT_PASSWORD=yes
    networks:
      default:
        ipv4_address: 172.2.200.33

# start docker in pool-network
networks:
  default:
    external:
      name: pool-network

